export enum EventNames {

    CORE_BEFORE_INIT = "CORE_BEFORE_INIT",
    CORE_AFTER_INIT = "CORE_AFTER_INIT",
    STARTUP = "STARTUP",
    END = "END",
    MODULES_BEFORE_PRELOAD = "MODULES_BEFORE_PRELOAD",
    MODULES_AFTER_PRELOAD = "MODULES_AFTER_PRELOAD",
    MODULES_BEFORE_LOAD = "MODULES_BEFORE_LOAD",
    MODULES_AFTER_LOAD = "MODULES_AFTER_LOAD",
    NEW_MODULE_REGISTERED = "NEW_MODULE_REGISTERED",
    NEW_MODULE_REGISTERED_WITH_KIND_ = "NEW_MODULE_REGISTERED_WITH_KIND_",

}